/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * ecommerce-api
 * Ecommerce API
 * OpenAPI spec version: 1.0.0
 */
import { fetcher } from '../lib/fetcher';
export interface BoLoginDto {
  username: string;
  password: string;
}

export interface BoRefreshTokenDto {
  refreshToken: string;
}

/**
 * @summary Back Office health check
 */
export type healthCheckResponse200 = {
  data: void
  status: 200
}

export type healthCheckResponseSuccess = (healthCheckResponse200) & {
  headers: Headers;
};
;

export type healthCheckResponse = (healthCheckResponseSuccess)

export const getHealthCheckUrl = () => {


  

  return `/bo/health`
}

export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {
  
  return fetcher<healthCheckResponse>(getHealthCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary BO username login
 */
export type loginResponse201 = {
  data: void
  status: 201
}

export type loginResponseSuccess = (loginResponse201) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = () => {


  

  return `/bo/auth/login`
}

export const login = async (boLoginDto: BoLoginDto, options?: RequestInit): Promise<loginResponse> => {
  
  return fetcher<loginResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      boLoginDto,)
  }
);}
  


/**
 * @summary BO refresh token rotation
 */
export type refreshResponse201 = {
  data: void
  status: 201
}

export type refreshResponseSuccess = (refreshResponse201) & {
  headers: Headers;
};
;

export type refreshResponse = (refreshResponseSuccess)

export const getRefreshUrl = () => {


  

  return `/bo/auth/refresh`
}

export const refresh = async (boRefreshTokenDto: BoRefreshTokenDto, options?: RequestInit): Promise<refreshResponse> => {
  
  return fetcher<refreshResponse>(getRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      boRefreshTokenDto,)
  }
);}
