/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * ecommerce-api
 * Ecommerce API
 * OpenAPI spec version: 1.0.0
 */
import { fetcher } from '../lib/fetcher';
export interface FoLoginDto {
  email: string;
  password: string;
}

export interface FoSocialLoginDto {
  /** social provider key */
  provider: string;
  accessToken: string;
}

export type FoQuoteDtoCustomerSegment = typeof FoQuoteDtoCustomerSegment[keyof typeof FoQuoteDtoCustomerSegment];


export const FoQuoteDtoCustomerSegment = {
  guest: 'guest',
  member: 'member',
} as const;

export interface FoQuoteDto {
  /** @minimum 1 */
  quantity: number;
  customerSegment?: FoQuoteDtoCustomerSegment;
  selectedOptionItemIds?: number[];
}

export type Login200DataUser = {
  email: string;
};

export type Login200Data = {
  scope: string;
  loginType: string;
  user: Login200DataUser;
};

export type Login200 = {
  success: boolean;
  code: string;
  message: string;
  data: Login200Data;
};

export type Login400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Login400Meta = {
  requestId?: string;
};

export type Login400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Login400ErrorsItem[];
  meta: Login400Meta;
};

export type Login401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Login401Meta = {
  requestId?: string;
};

export type Login401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Login401ErrorsItem[];
  meta: Login401Meta;
};

export type Login403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Login403Meta = {
  requestId?: string;
};

export type Login403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Login403ErrorsItem[];
  meta: Login403Meta;
};

export type Login404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Login404Meta = {
  requestId?: string;
};

export type Login404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Login404ErrorsItem[];
  meta: Login404Meta;
};

export type Login409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Login409Meta = {
  requestId?: string;
};

export type Login409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Login409ErrorsItem[];
  meta: Login409Meta;
};

export type Login500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Login500Meta = {
  requestId?: string;
};

export type Login500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Login500ErrorsItem[];
  meta: Login500Meta;
};

export type SocialLogin200Data = {
  scope: string;
  loginType: string;
  provider: string;
};

export type SocialLogin200 = {
  success: boolean;
  code: string;
  message: string;
  data: SocialLogin200Data;
};

export type SocialLogin400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type SocialLogin400Meta = {
  requestId?: string;
};

export type SocialLogin400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: SocialLogin400ErrorsItem[];
  meta: SocialLogin400Meta;
};

export type SocialLogin401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type SocialLogin401Meta = {
  requestId?: string;
};

export type SocialLogin401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: SocialLogin401ErrorsItem[];
  meta: SocialLogin401Meta;
};

export type SocialLogin403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type SocialLogin403Meta = {
  requestId?: string;
};

export type SocialLogin403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: SocialLogin403ErrorsItem[];
  meta: SocialLogin403Meta;
};

export type SocialLogin404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type SocialLogin404Meta = {
  requestId?: string;
};

export type SocialLogin404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: SocialLogin404ErrorsItem[];
  meta: SocialLogin404Meta;
};

export type SocialLogin409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type SocialLogin409Meta = {
  requestId?: string;
};

export type SocialLogin409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: SocialLogin409ErrorsItem[];
  meta: SocialLogin409Meta;
};

export type SocialLogin500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type SocialLogin500Meta = {
  requestId?: string;
};

export type SocialLogin500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: SocialLogin500ErrorsItem[];
  meta: SocialLogin500Meta;
};

export type Refresh200Data = {
  refreshed: boolean;
};

export type Refresh200 = {
  success: boolean;
  code: string;
  message: string;
  data: Refresh200Data;
};

export type Refresh400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Refresh400Meta = {
  requestId?: string;
};

export type Refresh400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Refresh400ErrorsItem[];
  meta: Refresh400Meta;
};

export type Refresh401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Refresh401Meta = {
  requestId?: string;
};

export type Refresh401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Refresh401ErrorsItem[];
  meta: Refresh401Meta;
};

export type Refresh403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Refresh403Meta = {
  requestId?: string;
};

export type Refresh403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Refresh403ErrorsItem[];
  meta: Refresh403Meta;
};

export type Refresh404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Refresh404Meta = {
  requestId?: string;
};

export type Refresh404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Refresh404ErrorsItem[];
  meta: Refresh404Meta;
};

export type Refresh409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Refresh409Meta = {
  requestId?: string;
};

export type Refresh409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Refresh409ErrorsItem[];
  meta: Refresh409Meta;
};

export type Refresh500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Refresh500Meta = {
  requestId?: string;
};

export type Refresh500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Refresh500ErrorsItem[];
  meta: Refresh500Meta;
};

export type Me200Data = {
  id: number;
  email: string;
  displayName: string;
};

export type Me200 = {
  success: boolean;
  code: string;
  message: string;
  data: Me200Data;
};

export type Me400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Me400Meta = {
  requestId?: string;
};

export type Me400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Me400ErrorsItem[];
  meta: Me400Meta;
};

export type Me401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Me401Meta = {
  requestId?: string;
};

export type Me401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Me401ErrorsItem[];
  meta: Me401Meta;
};

export type Me403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Me403Meta = {
  requestId?: string;
};

export type Me403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Me403ErrorsItem[];
  meta: Me403Meta;
};

export type Me404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Me404Meta = {
  requestId?: string;
};

export type Me404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Me404ErrorsItem[];
  meta: Me404Meta;
};

export type Me409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Me409Meta = {
  requestId?: string;
};

export type Me409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Me409ErrorsItem[];
  meta: Me409Meta;
};

export type Me500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Me500Meta = {
  requestId?: string;
};

export type Me500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Me500ErrorsItem[];
  meta: Me500Meta;
};

export type Tree200DataItemChildrenItem = { [key: string]: unknown };

export type Tree200DataItem = {
  id: number;
  /** @nullable */
  parentId: number | null;
  depth: number;
  path: string;
  name: string;
  slug: string;
  sortOrder: number;
  isActive: boolean;
  isVisible: boolean;
  isMainExposed: boolean;
  children: Tree200DataItemChildrenItem[];
};

export type Tree200 = {
  success: boolean;
  code: string;
  message: string;
  data: Tree200DataItem[];
};

export type Tree500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Tree500Meta = {
  requestId?: string;
};

export type Tree500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Tree500ErrorsItem[];
  meta: Tree500Meta;
};

export type Main200DataItem = {
  id: number;
  /** @nullable */
  parentId: number | null;
  depth: number;
  path: string;
  name: string;
  slug: string;
  sortOrder: number;
  isActive: boolean;
  isVisible: boolean;
  isMainExposed: boolean;
};

export type Main200 = {
  success: boolean;
  code: string;
  message: string;
  data: Main200DataItem[];
};

export type Main500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type Main500Meta = {
  requestId?: string;
};

export type Main500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: Main500ErrorsItem[];
  meta: Main500Meta;
};

export type ListProductsParams = {
storeId?: string;
categoryId?: string;
keyword?: string;
minMoq?: string;
maxMoq?: string;
};

export type ListProducts200DataItem = {
  id?: number;
  storeId?: number;
  /** @nullable */
  categoryId?: number | null;
  name?: string;
  slug?: string;
  moq?: number;
  moqInquiryOnly?: boolean;
  vatType?: string;
  vatRate?: number;
  isPrintable?: boolean;
  /** @nullable */
  printMethod?: string | null;
  /** @nullable */
  printArea?: string | null;
  /** @nullable */
  proofLeadTimeDays?: number | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  createdAt?: string;
  updatedAt?: string;
};

export type ListProducts200 = {
  success: boolean;
  code: string;
  message: string;
  data: ListProducts200DataItem[];
};

export type ListProducts400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListProducts400Meta = {
  requestId?: string;
};

export type ListProducts400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListProducts400ErrorsItem[];
  meta: ListProducts400Meta;
};

export type ListProducts401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListProducts401Meta = {
  requestId?: string;
};

export type ListProducts401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListProducts401ErrorsItem[];
  meta: ListProducts401Meta;
};

export type ListProducts403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListProducts403Meta = {
  requestId?: string;
};

export type ListProducts403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListProducts403ErrorsItem[];
  meta: ListProducts403Meta;
};

export type ListProducts404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListProducts404Meta = {
  requestId?: string;
};

export type ListProducts404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListProducts404ErrorsItem[];
  meta: ListProducts404Meta;
};

export type ListProducts409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListProducts409Meta = {
  requestId?: string;
};

export type ListProducts409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListProducts409ErrorsItem[];
  meta: ListProducts409Meta;
};

export type ListProducts500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListProducts500Meta = {
  requestId?: string;
};

export type ListProducts500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListProducts500ErrorsItem[];
  meta: ListProducts500Meta;
};

export type DetailProduct200DataMediaItem = {
  id?: number;
  type?: string;
  sourceType?: string;
  url?: string;
  /** @nullable */
  altText?: string | null;
  sortOrder?: number;
};

/**
 * @nullable
 */
export type DetailProduct200DataSeo = { [key: string]: unknown } | null;

export type DetailProduct200DataOptionGroupsItem = { [key: string]: unknown };

export type DetailProduct200DataSpecGroupsItem = { [key: string]: unknown };

export type DetailProduct200DataPriceTiersGuestItem = { [key: string]: unknown };

export type DetailProduct200DataPriceTiersMemberItem = { [key: string]: unknown };

export type DetailProduct200DataPriceTiers = {
  guest?: DetailProduct200DataPriceTiersGuestItem[];
  member?: DetailProduct200DataPriceTiersMemberItem[];
};

export type DetailProduct200DataShippingTiersItem = { [key: string]: unknown };

export type DetailProduct200Data = {
  id?: number;
  storeId?: number;
  /** @nullable */
  categoryId?: number | null;
  name?: string;
  slug?: string;
  status?: string;
  isVisible?: boolean;
  moq?: number;
  moqInquiryOnly?: boolean;
  baseSupplyCost?: number;
  vatType?: string;
  vatRate?: number;
  isPrintable?: boolean;
  /** @nullable */
  printMethod?: string | null;
  /** @nullable */
  printArea?: string | null;
  /** @nullable */
  proofLeadTimeDays?: number | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  media?: DetailProduct200DataMediaItem[];
  descriptionHtml?: string;
  /** @nullable */
  seo?: DetailProduct200DataSeo;
  tags?: string[];
  searchAliases?: string[];
  optionGroups?: DetailProduct200DataOptionGroupsItem[];
  specGroups?: DetailProduct200DataSpecGroupsItem[];
  priceTiers?: DetailProduct200DataPriceTiers;
  shippingTiers?: DetailProduct200DataShippingTiersItem[];
  createdAt?: string;
  updatedAt?: string;
};

export type DetailProduct200 = {
  success: boolean;
  code: string;
  message: string;
  data: DetailProduct200Data;
};

export type DetailProduct400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type DetailProduct400Meta = {
  requestId?: string;
};

export type DetailProduct400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: DetailProduct400ErrorsItem[];
  meta: DetailProduct400Meta;
};

export type DetailProduct401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type DetailProduct401Meta = {
  requestId?: string;
};

export type DetailProduct401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: DetailProduct401ErrorsItem[];
  meta: DetailProduct401Meta;
};

export type DetailProduct403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type DetailProduct403Meta = {
  requestId?: string;
};

export type DetailProduct403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: DetailProduct403ErrorsItem[];
  meta: DetailProduct403Meta;
};

export type DetailProduct404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type DetailProduct404Meta = {
  requestId?: string;
};

export type DetailProduct404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: DetailProduct404ErrorsItem[];
  meta: DetailProduct404Meta;
};

export type DetailProduct409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type DetailProduct409Meta = {
  requestId?: string;
};

export type DetailProduct409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: DetailProduct409ErrorsItem[];
  meta: DetailProduct409Meta;
};

export type DetailProduct500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type DetailProduct500Meta = {
  requestId?: string;
};

export type DetailProduct500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: DetailProduct500ErrorsItem[];
  meta: DetailProduct500Meta;
};

export type QuoteProduct200DataAppliedTier = {
  id?: number;
  minQty?: number;
  marginRate?: number;
  unitPrice?: number;
};

export type QuoteProduct200Data = {
  target?: string;
  productId?: number;
  productName?: string;
  customerSegment?: string;
  quantity?: number;
  moq?: number;
  vatType?: string;
  vatRate?: number;
  appliedTier?: QuoteProduct200DataAppliedTier;
  selectedOptionItemIds?: number[];
  optionAdjustmentUnitPrice?: number;
  optionAdjustmentSupplyCost?: number;
  unitPrice?: number;
  supplyUnitCost?: number;
  supplyTotal?: number;
  subtotalExVat?: number;
  vatAmount?: number;
  shippingFee?: number;
  totalAmount?: number;
  estimatedMargin?: number;
};

export type QuoteProduct200 = {
  success: boolean;
  code: string;
  message: string;
  data: QuoteProduct200Data;
};

export type QuoteProduct400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type QuoteProduct400Meta = {
  requestId?: string;
};

export type QuoteProduct400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: QuoteProduct400ErrorsItem[];
  meta: QuoteProduct400Meta;
};

export type QuoteProduct401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type QuoteProduct401Meta = {
  requestId?: string;
};

export type QuoteProduct401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: QuoteProduct401ErrorsItem[];
  meta: QuoteProduct401Meta;
};

export type QuoteProduct403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type QuoteProduct403Meta = {
  requestId?: string;
};

export type QuoteProduct403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: QuoteProduct403ErrorsItem[];
  meta: QuoteProduct403Meta;
};

export type QuoteProduct404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type QuoteProduct404Meta = {
  requestId?: string;
};

export type QuoteProduct404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: QuoteProduct404ErrorsItem[];
  meta: QuoteProduct404Meta;
};

export type QuoteProduct409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type QuoteProduct409Meta = {
  requestId?: string;
};

export type QuoteProduct409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: QuoteProduct409ErrorsItem[];
  meta: QuoteProduct409Meta;
};

export type QuoteProduct500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type QuoteProduct500Meta = {
  requestId?: string;
};

export type QuoteProduct500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: QuoteProduct500ErrorsItem[];
  meta: QuoteProduct500Meta;
};

export type ListStoreProductsParams = {
categoryId?: string;
keyword?: string;
minMoq?: string;
maxMoq?: string;
};

export type ListStoreProducts200DataItem = {
  id?: number;
  storeId?: number;
  /** @nullable */
  categoryId?: number | null;
  name?: string;
  slug?: string;
  moq?: number;
  moqInquiryOnly?: boolean;
  vatType?: string;
  vatRate?: number;
  isPrintable?: boolean;
  /** @nullable */
  printMethod?: string | null;
  /** @nullable */
  printArea?: string | null;
  /** @nullable */
  proofLeadTimeDays?: number | null;
  /** @nullable */
  thumbnailUrl?: string | null;
  createdAt?: string;
  updatedAt?: string;
};

export type ListStoreProducts200 = {
  success: boolean;
  code: string;
  message: string;
  data: ListStoreProducts200DataItem[];
};

export type ListStoreProducts400ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListStoreProducts400Meta = {
  requestId?: string;
};

export type ListStoreProducts400 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListStoreProducts400ErrorsItem[];
  meta: ListStoreProducts400Meta;
};

export type ListStoreProducts401ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListStoreProducts401Meta = {
  requestId?: string;
};

export type ListStoreProducts401 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListStoreProducts401ErrorsItem[];
  meta: ListStoreProducts401Meta;
};

export type ListStoreProducts403ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListStoreProducts403Meta = {
  requestId?: string;
};

export type ListStoreProducts403 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListStoreProducts403ErrorsItem[];
  meta: ListStoreProducts403Meta;
};

export type ListStoreProducts404ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListStoreProducts404Meta = {
  requestId?: string;
};

export type ListStoreProducts404 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListStoreProducts404ErrorsItem[];
  meta: ListStoreProducts404Meta;
};

export type ListStoreProducts409ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListStoreProducts409Meta = {
  requestId?: string;
};

export type ListStoreProducts409 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListStoreProducts409ErrorsItem[];
  meta: ListStoreProducts409Meta;
};

export type ListStoreProducts500ErrorsItem = {
  field?: string;
  reason?: string;
};

export type ListStoreProducts500Meta = {
  requestId?: string;
};

export type ListStoreProducts500 = {
  success: boolean;
  code: string;
  message: string;
  errors?: ListStoreProducts500ErrorsItem[];
  meta: ListStoreProducts500Meta;
};

/**
 * @summary Front Office health check
 */
export type healthCheckResponse200 = {
  data: void
  status: 200
}

export type healthCheckResponseSuccess = (healthCheckResponse200) & {
  headers: Headers;
};
;

export type healthCheckResponse = (healthCheckResponseSuccess)

export const getHealthCheckUrl = () => {


  

  return `/fo/health`
}

export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {
  
  return fetcher<healthCheckResponse>(getHealthCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary FO email login (httpOnly cookie)
 */
export type loginResponse200 = {
  data: Login200
  status: 200
}

export type loginResponse400 = {
  data: Login400
  status: 400
}

export type loginResponse401 = {
  data: Login401
  status: 401
}

export type loginResponse403 = {
  data: Login403
  status: 403
}

export type loginResponse404 = {
  data: Login404
  status: 404
}

export type loginResponse409 = {
  data: Login409
  status: 409
}

export type loginResponse500 = {
  data: Login500
  status: 500
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse400 | loginResponse401 | loginResponse403 | loginResponse404 | loginResponse409 | loginResponse500) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {


  

  return `/fo/auth/login`
}

export const login = async (foLoginDto: FoLoginDto, options?: RequestInit): Promise<loginResponse> => {
  
  return fetcher<loginResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      foLoginDto,)
  }
);}
  


/**
 * @summary FO social login (future-ready placeholder)
 */
export type socialLoginResponse200 = {
  data: SocialLogin200
  status: 200
}

export type socialLoginResponse400 = {
  data: SocialLogin400
  status: 400
}

export type socialLoginResponse401 = {
  data: SocialLogin401
  status: 401
}

export type socialLoginResponse403 = {
  data: SocialLogin403
  status: 403
}

export type socialLoginResponse404 = {
  data: SocialLogin404
  status: 404
}

export type socialLoginResponse409 = {
  data: SocialLogin409
  status: 409
}

export type socialLoginResponse500 = {
  data: SocialLogin500
  status: 500
}

export type socialLoginResponseSuccess = (socialLoginResponse200) & {
  headers: Headers;
};
export type socialLoginResponseError = (socialLoginResponse400 | socialLoginResponse401 | socialLoginResponse403 | socialLoginResponse404 | socialLoginResponse409 | socialLoginResponse500) & {
  headers: Headers;
};

export type socialLoginResponse = (socialLoginResponseSuccess | socialLoginResponseError)

export const getSocialLoginUrl = () => {


  

  return `/fo/auth/social-login`
}

export const socialLogin = async (foSocialLoginDto: FoSocialLoginDto, options?: RequestInit): Promise<socialLoginResponse> => {
  
  return fetcher<socialLoginResponse>(getSocialLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      foSocialLoginDto,)
  }
);}
  


/**
 * @summary FO refresh token rotation (httpOnly cookie)
 */
export type refreshResponse200 = {
  data: Refresh200
  status: 200
}

export type refreshResponse400 = {
  data: Refresh400
  status: 400
}

export type refreshResponse401 = {
  data: Refresh401
  status: 401
}

export type refreshResponse403 = {
  data: Refresh403
  status: 403
}

export type refreshResponse404 = {
  data: Refresh404
  status: 404
}

export type refreshResponse409 = {
  data: Refresh409
  status: 409
}

export type refreshResponse500 = {
  data: Refresh500
  status: 500
}

export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponse400 | refreshResponse401 | refreshResponse403 | refreshResponse404 | refreshResponse409 | refreshResponse500) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {


  

  return `/fo/auth/refresh`
}

export const refresh = async ( options?: RequestInit): Promise<refreshResponse> => {
  
  return fetcher<refreshResponse>(getRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  


/**
 * @summary FO 본인 정보 조회
 */
export type meResponse200 = {
  data: Me200
  status: 200
}

export type meResponse400 = {
  data: Me400
  status: 400
}

export type meResponse401 = {
  data: Me401
  status: 401
}

export type meResponse403 = {
  data: Me403
  status: 403
}

export type meResponse404 = {
  data: Me404
  status: 404
}

export type meResponse409 = {
  data: Me409
  status: 409
}

export type meResponse500 = {
  data: Me500
  status: 500
}

export type meResponseSuccess = (meResponse200) & {
  headers: Headers;
};
export type meResponseError = (meResponse400 | meResponse401 | meResponse403 | meResponse404 | meResponse409 | meResponse500) & {
  headers: Headers;
};

export type meResponse = (meResponseSuccess | meResponseError)

export const getMeUrl = () => {


  

  return `/fo/auth/me`
}

export const me = async ( options?: RequestInit): Promise<meResponse> => {
  
  return fetcher<meResponse>(getMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary FO 카테고리 트리 조회
 */
export type treeResponse200 = {
  data: Tree200
  status: 200
}

export type treeResponse500 = {
  data: Tree500
  status: 500
}

export type treeResponseSuccess = (treeResponse200) & {
  headers: Headers;
};
export type treeResponseError = (treeResponse500) & {
  headers: Headers;
};

export type treeResponse = (treeResponseSuccess | treeResponseError)

export const getTreeUrl = () => {


  

  return `/fo/categories/tree`
}

export const tree = async ( options?: RequestInit): Promise<treeResponse> => {
  
  return fetcher<treeResponse>(getTreeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary FO 메인 노출 카테고리 조회
 */
export type mainResponse200 = {
  data: Main200
  status: 200
}

export type mainResponse500 = {
  data: Main500
  status: 500
}

export type mainResponseSuccess = (mainResponse200) & {
  headers: Headers;
};
export type mainResponseError = (mainResponse500) & {
  headers: Headers;
};

export type mainResponse = (mainResponseSuccess | mainResponseError)

export const getMainUrl = () => {


  

  return `/fo/categories/main`
}

export const main = async ( options?: RequestInit): Promise<mainResponse> => {
  
  return fetcher<mainResponse>(getMainUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary FO 상품 목록 조회
 */
export type listProductsResponse200 = {
  data: ListProducts200
  status: 200
}

export type listProductsResponse400 = {
  data: ListProducts400
  status: 400
}

export type listProductsResponse401 = {
  data: ListProducts401
  status: 401
}

export type listProductsResponse403 = {
  data: ListProducts403
  status: 403
}

export type listProductsResponse404 = {
  data: ListProducts404
  status: 404
}

export type listProductsResponse409 = {
  data: ListProducts409
  status: 409
}

export type listProductsResponse500 = {
  data: ListProducts500
  status: 500
}

export type listProductsResponseSuccess = (listProductsResponse200) & {
  headers: Headers;
};
export type listProductsResponseError = (listProductsResponse400 | listProductsResponse401 | listProductsResponse403 | listProductsResponse404 | listProductsResponse409 | listProductsResponse500) & {
  headers: Headers;
};

export type listProductsResponse = (listProductsResponseSuccess | listProductsResponseError)

export const getListProductsUrl = (params?: ListProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/fo/products?${stringifiedParams}` : `/fo/products`
}

export const listProducts = async (params?: ListProductsParams, options?: RequestInit): Promise<listProductsResponse> => {
  
  return fetcher<listProductsResponse>(getListProductsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary FO 상품 상세 조회
 */
export type detailProductResponse200 = {
  data: DetailProduct200
  status: 200
}

export type detailProductResponse400 = {
  data: DetailProduct400
  status: 400
}

export type detailProductResponse401 = {
  data: DetailProduct401
  status: 401
}

export type detailProductResponse403 = {
  data: DetailProduct403
  status: 403
}

export type detailProductResponse404 = {
  data: DetailProduct404
  status: 404
}

export type detailProductResponse409 = {
  data: DetailProduct409
  status: 409
}

export type detailProductResponse500 = {
  data: DetailProduct500
  status: 500
}

export type detailProductResponseSuccess = (detailProductResponse200) & {
  headers: Headers;
};
export type detailProductResponseError = (detailProductResponse400 | detailProductResponse401 | detailProductResponse403 | detailProductResponse404 | detailProductResponse409 | detailProductResponse500) & {
  headers: Headers;
};

export type detailProductResponse = (detailProductResponseSuccess | detailProductResponseError)

export const getDetailProductUrl = (slug: string,) => {


  

  return `/fo/products/${slug}`
}

export const detailProduct = async (slug: string, options?: RequestInit): Promise<detailProductResponse> => {
  
  return fetcher<detailProductResponse>(getDetailProductUrl(slug),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary FO 상품 견적 계산
 */
export type quoteProductResponse200 = {
  data: QuoteProduct200
  status: 200
}

export type quoteProductResponse400 = {
  data: QuoteProduct400
  status: 400
}

export type quoteProductResponse401 = {
  data: QuoteProduct401
  status: 401
}

export type quoteProductResponse403 = {
  data: QuoteProduct403
  status: 403
}

export type quoteProductResponse404 = {
  data: QuoteProduct404
  status: 404
}

export type quoteProductResponse409 = {
  data: QuoteProduct409
  status: 409
}

export type quoteProductResponse500 = {
  data: QuoteProduct500
  status: 500
}

export type quoteProductResponseSuccess = (quoteProductResponse200) & {
  headers: Headers;
};
export type quoteProductResponseError = (quoteProductResponse400 | quoteProductResponse401 | quoteProductResponse403 | quoteProductResponse404 | quoteProductResponse409 | quoteProductResponse500) & {
  headers: Headers;
};

export type quoteProductResponse = (quoteProductResponseSuccess | quoteProductResponseError)

export const getQuoteProductUrl = (id: number,) => {


  

  return `/fo/products/${id}/quote`
}

export const quoteProduct = async (id: number,
    foQuoteDto: FoQuoteDto, options?: RequestInit): Promise<quoteProductResponse> => {
  
  return fetcher<quoteProductResponse>(getQuoteProductUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      foQuoteDto,)
  }
);}
  


/**
 * @summary FO 스토어별 상품 목록 조회
 */
export type listStoreProductsResponse200 = {
  data: ListStoreProducts200
  status: 200
}

export type listStoreProductsResponse400 = {
  data: ListStoreProducts400
  status: 400
}

export type listStoreProductsResponse401 = {
  data: ListStoreProducts401
  status: 401
}

export type listStoreProductsResponse403 = {
  data: ListStoreProducts403
  status: 403
}

export type listStoreProductsResponse404 = {
  data: ListStoreProducts404
  status: 404
}

export type listStoreProductsResponse409 = {
  data: ListStoreProducts409
  status: 409
}

export type listStoreProductsResponse500 = {
  data: ListStoreProducts500
  status: 500
}

export type listStoreProductsResponseSuccess = (listStoreProductsResponse200) & {
  headers: Headers;
};
export type listStoreProductsResponseError = (listStoreProductsResponse400 | listStoreProductsResponse401 | listStoreProductsResponse403 | listStoreProductsResponse404 | listStoreProductsResponse409 | listStoreProductsResponse500) & {
  headers: Headers;
};

export type listStoreProductsResponse = (listStoreProductsResponseSuccess | listStoreProductsResponseError)

export const getListStoreProductsUrl = (storeId: number,
    params?: ListStoreProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/fo/stores/${storeId}/products?${stringifiedParams}` : `/fo/stores/${storeId}/products`
}

export const listStoreProducts = async (storeId: number,
    params?: ListStoreProductsParams, options?: RequestInit): Promise<listStoreProductsResponse> => {
  
  return fetcher<listStoreProductsResponse>(getListStoreProductsUrl(storeId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
