/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * ecommerce-api
 * Ecommerce API
 * OpenAPI spec version: 1.0.0
 */
import { fetcher } from '../lib/fetcher';
export interface FoLoginDto {
  email: string;
  password: string;
}

export interface FoSocialLoginDto {
  /** social provider key */
  provider: string;
  accessToken: string;
}

export interface FoRefreshTokenDto {
  refreshToken: string;
}

/**
 * @summary Front Office health check
 */
export type healthCheckResponse200 = {
  data: void
  status: 200
}

export type healthCheckResponseSuccess = (healthCheckResponse200) & {
  headers: Headers;
};
;

export type healthCheckResponse = (healthCheckResponseSuccess)

export const getHealthCheckUrl = () => {


  

  return `/fo/health`
}

export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {
  
  return fetcher<healthCheckResponse>(getHealthCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  


/**
 * @summary FO email login
 */
export type loginResponse201 = {
  data: void
  status: 201
}

export type loginResponseSuccess = (loginResponse201) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = () => {


  

  return `/fo/auth/login`
}

export const login = async (foLoginDto: FoLoginDto, options?: RequestInit): Promise<loginResponse> => {
  
  return fetcher<loginResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      foLoginDto,)
  }
);}
  


/**
 * @summary FO social login (future-ready placeholder)
 */
export type socialLoginResponse201 = {
  data: void
  status: 201
}

export type socialLoginResponseSuccess = (socialLoginResponse201) & {
  headers: Headers;
};
;

export type socialLoginResponse = (socialLoginResponseSuccess)

export const getSocialLoginUrl = () => {


  

  return `/fo/auth/social-login`
}

export const socialLogin = async (foSocialLoginDto: FoSocialLoginDto, options?: RequestInit): Promise<socialLoginResponse> => {
  
  return fetcher<socialLoginResponse>(getSocialLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      foSocialLoginDto,)
  }
);}
  


/**
 * @summary FO refresh token rotation
 */
export type refreshResponse201 = {
  data: void
  status: 201
}

export type refreshResponseSuccess = (refreshResponse201) & {
  headers: Headers;
};
;

export type refreshResponse = (refreshResponseSuccess)

export const getRefreshUrl = () => {


  

  return `/fo/auth/refresh`
}

export const refresh = async (foRefreshTokenDto: FoRefreshTokenDto, options?: RequestInit): Promise<refreshResponse> => {
  
  return fetcher<refreshResponse>(getRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      foRefreshTokenDto,)
  }
);}
